// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $('#search').on('submit', function(e) {
      var masterResponse, searchTerm;
      searchTerm = $('#searchField').val();
      masterResponse = $.ajax("http://www.omdbapi.com/?s=" + searchTerm, {
        dataType: "json"
      });
      return masterResponse.done(function(data) {
        var detail, imdb, movie, movies, _i, _len, _results;
        movies = data.Search;
        _results = [];
        for (_i = 0, _len = movies.length; _i < _len; _i++) {
          movie = movies[_i];
          imdb = movie.imdbID;
          detail = $.ajax("http://www.omdbapi.com/?i=" + imdb, {
            dataType: 'json'
          });
          console.log("http://www.omdbapi.com/?i=" + imdb);
          _results.push(detail.done(function(movie) {
            var rating;
            rating = movie.imdbRating;
            console.log(rating);
            rating = parseFloat(movie.imdbRating);
            if (rating <= 2) {
              $('.nope').append(movie.Title);
            } else if (rating <= 4) {
              $('.meh').append(movie.Title);
            } else if (rating <= 6) {
              $('.ok').append(movie.Title);
            } else if (rating <= 8) {
              $('.veryGood').append(movie.Title);
            } else {
              $('.fantastic').append(movie.Title);
            }
            $('.detail .title').html(movie.Title);
            $('.detail .poster').html(poster);
            $('.detail .year').html(movie.Year);
            $('.detail .plot').html(movie.Plot);
            $('.detail .rating').html(movie.imdbRating);
            return console.log(movie.imdbRating);
          }));
        }
        return _results;
      });
    });
    return $('#reset').click(function() {
      $('.movies').html("");
      return $('.fantastic').html("");
    });
  });

}).call(this);

//# sourceMappingURL=main.map
